# Generated by Django 5.0.6 on 2024-06-14 05:02

import django.core.files.storage
import django.db.models.deletion
import tabla.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\APLICATIVOS DJANGO\\Restaurante\\micariñito\\media'), upload_to=tabla.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\APLICATIVOS DJANGO\\Restaurante\\micariñito\\media'), upload_to=tabla.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='GananciaMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(unique=True)),
                ('total_reservas', models.IntegerField(default=0)),
                ('total_registros_venta', models.IntegerField(default=0)),
                ('ganancia_reservas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ganancia_registros_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\APLICATIVOS DJANGO\\Restaurante\\micariñito\\media'), upload_to=tabla.models.get_upload_path)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabla.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PromocionDePlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(null=True)),
                ('precio_descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\APLICATIVOS DJANGO\\Restaurante\\micariñito\\media'), upload_to=tabla.models.get_upload_path)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabla.plato')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('bebidas', models.ManyToManyField(blank=True, to='tabla.bebida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabla.cliente')),
                ('entradas', models.ManyToManyField(blank=True, to='tabla.entrada')),
                ('platos', models.ManyToManyField(to='tabla.plato')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaDeMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_personas', models.IntegerField()),
                ('numero_mesa', models.IntegerField()),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hora', models.TimeField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha_reg', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabla.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tabla.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(max_length=200)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabla.usuario')),
            ],
        ),
    ]
